### ISSUE TITLE
sequence alignment (any specific filtering needed or not)?

### ISSUE THREAD

**Issue by curiousa** [ElofssonLab/PconsC4#3]
Hello there, 

I could run pconsC4 successfully for some fasta alignments but not the other. I couldn't figure out the possible cause of why certain alignments are not acceptable (see the error message I get below). Could you please let me know if there are any specific values accepted for alignment length, number of sequences, etc. 

Thanks,
Alina

The error message I get is the following:

>>> pred_3 = pconsc4.predict(model, 'cadtry2.fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/pconsc4/run.py", line 97, in predict
    return predict_contacts(model, alignment, verbose)
  File "/ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/pconsc4/run.py", line 101, in predict_contacts
    feat_dict, L = _generate_features(alignment, verbose)
  File "/ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/pconsc4/run.py", line 37, in _generate_features
    self_info, part_entr, seq = process_a3m(fname)
  File "pconsc4/parsing/_load_data.pyx", line 184, in pconsc4.parsing._load_data.process_a3m
  File "pconsc4/parsing/_load_data.pyx", line 67, in pconsc4.parsing._load_data.load_a3m
ValueError: setting an array element with a sequence.

**Comment by Dapid** [comment]
Sorry, I missed this issue when you submitted it. There are not limits in depth or size, but the alignments must be without line wrapping: that is, each sequence must be contained in one line. Your error suggests that you have wrap around:

```
>seq1
AAAFAPA
AA
>seq2
AABAPA
AB
```
Here are some examples: https://github.com/ElofssonLab/pyGaussDCA/tree/master/tests/data

If that is not the case, can you upload a failing example so I can look at it?
